### PR TITLE
Added pyrad config files for notebooks 1-2 (Swiss thunderstorm)

### PR DESCRIPTION
**Pull request by wolfidan**
Dear all,

I added pyrad config files to show how parts of notebooks 1 and 2 with Swiss weather radar data could be automatized. This is meant as a quick example I would cover at the very end of the pyart section of the course. I won't go into all details but I will show that it's possible.

In the background I did some harmonization of our pyart fork with the ARM fork and some updates to pyrad so that pyrad can run seamlessly with ARM's version or our version of pyart. However I'm still waiting for the PR I did for pyart ARM to be accepted for this whole thing to work, because it implements the function _subset_radar_ which is used in pyrad. Hopefully this will be done before ERAD2022.

Cheers,
Daniel W.

### CODE REVIEW

**Comment by wolfidan** [comment]
Note sure why this fails, but I think it has nothing to do with my PR, is the binder service down?

**Comment by kmuehlbauer** [comment]
@wolfidan Yes, the binder service is down. This started to happen 3 days ago, as the nightly builds are affected too. 

Maybe @scollis can get some information from the pangeo folks.

**Comment by kmuehlbauer** [comment]
But the docker build is OK, at least it looks like.

**Comment by mgrover1** [comment]
I need to update the path to the binder! Taking care of that today.

**Comment by mgrover1** [comment]
> In the background I did some harmonization of our pyart fork with the ARM fork and some updates to pyrad so that pyrad can run seamlessly with ARM's version or our version of pyart. However I'm still waiting for the PR I did for pyart ARM to be accepted for this whole thing to work, because it implements the function _subset_radar_ which is used in pyrad. Hopefully this will be done before ERAD2022.

@wolfidan - this PR will be in by the meeting, and we will cut a new release with this. We ran into issues with TRMM_RSL which we are currently troubleshooting, leading to failed doc builds. 

Once this is resolved, we can merge away! Sorry for the delay.

**Review by mgrover1 — APPROVED** [review]
Tests seem to be running, looks great!

**Comment by mgrover1** [comment]
@wolfidan are you okay if we merge?

**Comment by wolfidan** [comment]
Amazing! Thank you so much @mgrover1 !
Yes we can merge,
Cheers,
Daniel W.

**Pull request merged**
