### PR TITLE
Use most recent version of pyart

### LINKED ISSUE #55: Missing subset_radar in pyART
Hello @mgrover1 ,

I'm really sorry for pushing this, but do you think it would be possible to release a new *arm_pyart* conda package until the course.?Because pyrad relies on the availability of the *subset_radar* function which is in now in the master of *arm_pyart* but not yet in the conda package.

Thank you very much,
Cheers,
Daniel

### PR DESCRIPTION
**Pull request by mgrover1**
Use the most recent version of Py-ART directly from the github repository

Closes #55

### CODE REVIEW

**Comment by mgrover1** [comment]
@wolfidan - this is one approach we can use to use the functionality right now. We are still sorting out TRMM RSL feedstock issues, and want to hold off on cutting a new release of Py-ART until this is resolved. I think we should give this is a shot, and check to ensure everything works as expected.

**Comment by kmuehlbauer** [comment]
Note to self and xref #56: This PR is building baltrad bropo correcly.

**Comment by kmuehlbauer** [comment]
@mgrover1 Is this good to go? From looking at the notebooks it seems fine. At least they are running and creating output.

**Comment by mgrover1** [comment]
Yup! Good to go!

**Comment by kmuehlbauer** [comment]
I'm still wondering what happened with the last push build of baltrad bropo. Maybe it will magically heal without touching it.

**Comment by wolfidan** [comment]
@mgrover1 , that's a good option, thank you.

I'll definitely check it out when you release a new _arm_pyart_ package, because despite trying several options, I couldn't get a conda release with TRMM support. So thanks in advance for your work in this direction

**Pull request merged**
