### PR TITLE
MNT: fixup notebooks

### PR DESCRIPTION
**Pull request by kmuehlbauer**
As mentioned in #49 there is an issue with some versions of jupyterlab. I've set all notebooks to version 4.4 for now (removing all cell id's). 

Further fixes/changes:

- move pyrad notebooks/data/images into notebooks-folder
- add pyrad notebooks to toc
- fixup notebooks (format 4.4, inline images and more)

@wolfidan This should not change anything for the notebooks. I've tested locally with success. If the build looks OK, this would be good to go.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
The inline images are not displayed after the notebooks are being processed. Need to investigate.

**Comment by kmuehlbauer** [comment]
Now the inline images work as expected. Had to remove the html div tags.

@DanielMichelson Just a heads-up: I've updated the baltrad2wradlib notebook to the latest wradlib (1.16.2, yet unreleased). Finishing this up now over at wradlib.

**Comment by wolfidan** [comment]
@kmuehlbauer , thank you very much for checking this out !

**Comment by kmuehlbauer** [comment]
@wolfidan @maxgrover1 I've checked the notebooks by quickly scanning through. Beside the half-brohen baltrad2wradlib (which will self-repair after wradlib 1.16.2) everything looks good so far.

**Pull request merged**
