### PR TITLE
power point presentation for the package overview session

### PR DESCRIPTION
**Pull request by jfigui**
Hello all,

I am uploading a draft version of the presentation for the session Overview of the open source radar processing packages (09:45 to 10:30).

In the end @wolfidan and myself decided that it would be easier to do it in classical power point rather than notebooks.

I am targeting a 30 minutes talk and assuming there will be 15 minutes questions. As you will see, the presentation is not really fancy but I wanted to be able to discuss the draft.

What I need from you:
- Tell me if the contents match your expectations
- Tell me if you are happy with the way I present your respective packages
- Complement slides 4, 5 and 6 with interesting open source software packages and radar functionality
- Provide any advise, criticism, questioning you feel like

I am hoping to be on holiday by the 8th of August so please send me your advise by the beginning of next week

Thanks a lot!

Jordi

### CODE REVIEW

**Comment by jfigui** [comment]
Just pinning @kmuehlbauer @mgrover1 @mike-dixon @DanielMichelson @wolfidan about this pull request :)

**Comment by mgrover1** [comment]
Looks great! Ready to merge?

**Review by mgrover1 — APPROVED** [review]
Thanks for putting this together!

**Comment by jfigui** [comment]
I will wait a couple of days for feedback and then I will merge

**Comment by kmuehlbauer** [comment]
Looks good from wradlib side. :+1:

**Pull request merged**
