### PR TITLE
added missing images in notebooks + adjustment for new join_radar fct

### PR DESCRIPTION
**Pull request by wolfidan**
I'm sorry I realized I had forgotten to also _include the 2 images I link in the notebooks_. 
I have also taken the opportunity to _adjust some part of the code to new pyart join_radar function_ in order to perform dealiasing on the merged radar object instead of doing it separately before merging.

Thank you very much.
Daniel

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@wolfidan You could push the notebooks in a clean state, without ouput cells. That would make any review easier and keeps the git a bit cleaner.

The notebooks,  at least those in the norltebook-folder, are stripped and cleaned anyway when creating the docker image.

**Comment by mgrover1** [comment]
I can also enable reviewnb (https://www.reviewnb.com) here to make it easier to leave comments and suggestions on notebooks.

It makes diffing them a lot cleaner!

**Comment by mgrover1** [comment]
I would need access at the organization level with Open Radar though

**Comment by kmuehlbauer** [comment]
@mgrover1 I've currently no means to see (GitHub mobile), if I'm able to give you permissions on the org. But @scollis should have these powers.

**Comment by kmuehlbauer** [comment]
@wolfidan The link-check can be quite a bit of a nuisance but it will check if all the links which will end up in the final page can be reached. I've seen one link to wradlib docu had a "1" <-> "2" swap somewhere (CfRadial1 vs Cfradial2), so the link broke at that point. HTH.

**Comment by wolfidan** [comment]
Thanks @kmuehlbauer , it seems I managed to fix it.

**Review by mgrover1 — APPROVED** [review]

**Comment by kmuehlbauer** [comment]
@wolfidan Great that it works now. Can you have another check if the notebooks are clean (no output cells)? I've tried to render this on android but it doesn't let me look at the notebook sources. 😥 Oterwise, let's get this! :+1:

**Review by kmuehlbauer — APPROVED** [review]

**Comment by wolfidan** [comment]
I think it should be better in the last commit. Also I have fixed in issue with the attached images.

**Comment by mgrover1** [comment]
The notebooks look great! Can we go ahead and merge?

**Pull request merged**
