### PR TITLE
ADD: update wradlib version to 1.16.2

### PR DESCRIPTION
**Pull request by kmuehlbauer**
This will fix the currently broken `baltrad2wradlib` notebook.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Fixed! The notebooks should now be ready with respect to baltrad, pyart/pyrad and wradlib. I'll merge right away.

LROSE is still in the works, @mgrover1 and @mike-dixon?

**Comment by mgrover1** [comment]
We are chatting in a couple minutes - do you want to join the call @kmuehlbauer ?

**Comment by kmuehlbauer** [comment]
That would be a nice thing @mgrover1, but I have an appointment in half an hour. Let me know, if I can help/test with anything later today or tomorrow.

**Comment by mgrover1** [comment]
No worries! I will make sure to ping you once they are ready for review.

**Pull request merged**
