### PR TITLE
FIX: build system issues

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- This is correcting the remaining issues with the `CONDA_PREFXI` vs `CONDA_PREFIX` typo.
- PROJ_NETWORK env variable
- add Baltrad notebooks to toc
- more environment output for debugging/overview purpose

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@DanielMichelson This in combination with #47 should get Baltrad back in business. I'll check the Baltrad notebooks to be absolutely sure.

**Comment by kmuehlbauer** [comment]
There are issues with the Python environment. Not sure if they stem from the recent shapely/cartopy problem. I'll investigate locally.

**Comment by kmuehlbauer** [comment]
Locally at least the wradlib2baltrad notebook (which breaks currently on CI) works as expected (using repo2docker). I've added a notebook here which prints out some information about the python environment. Maybe there is some hint, what is broken here.

**Comment by kmuehlbauer** [comment]
> There are issues with the Python environment. Not sure if they stem from the recent shapely/cartopy problem. I'll investigate locally.

wradlib uses GDAL which uses PROJ. PROJ used to have it's transformation database inside the package. That changed a while back. Setting env var `PROJ_NETWORK=ON` enables PROJ to retrieve needed transformations from network resources.

**Comment by kmuehlbauer** [comment]
@DanielMichelson The pyart2baltrad notebooks bear a very ancient nbformat (3.0). This is obviously not detected by the bookbuilder and so these notebooks are not run automatically. They might have to be updated to a more recent version (4.4 would work well).

**Comment by kmuehlbauer** [comment]
So, it looks like the environment for the notebook server is not derived from the user profile. 

We could use (in theory) some env file with the needed environment variables or find some other means to do. Starting the notebook server from an activated environment would be best, IMHO, to have all activation scripts processed.

**Comment by kmuehlbauer** [comment]
The pyart2baltrad notebooks could not be processed because they were missing at the right location. I'll add the necessary copy command.

**Comment by kmuehlbauer** [comment]
Got lost in the two different build scenarios. Hope that activating the notebook environment within the book build will work around the current issues.

**Comment by kmuehlbauer** [comment]
Note to self: Keep in mind that we have two workflows, one for PR and one for PUSH. :grimacing:

**Comment by kmuehlbauer** [comment]
:crossed_fingers: that this works for PULL Requests now. Should work for PUSH (as it worked there before).

**Comment by kmuehlbauer** [comment]
I've no explanation for the differences:

This PR:
https://openradarscience.org/erad2022/_preview/48/notebooks/baltrad2wradlib/baltrad2wradlib.html

The latest PUSH to main:
https://openradarscience.org/erad2022/notebooks/baltrad2wradlib/baltrad2wradlib.html

There is obviously some difference in the setup of the book environment. For push the docker container is used directly, for pull request this is done via a docker-run-action. Good chance that via that action the environment is missing some variables. That's unfortunate but we have to live with. If someone has any idea how to track down the root cause, please let me know.

The baltrad issues should be finally cleared with this PR.

@mgrover1 This is ready from my side.

**Review by mgrover1 — APPROVED** [review]

**Comment by mgrover1** [comment]
LGTM!

**Comment by kmuehlbauer** [comment]
That was a tough ride! Thanks @DanielMichelson for bringing this up.

**Comment by DanielMichelson** [comment]
THANK YOU SOOO MUCH @kmuehlbauer! You are a hero!
Thanks also @mgrover1 for your support, and for accepting the PR!
I am now successfully updating the BALTRAD notebooks! I'll let you know when they are ready.

**Pull request merged**
