### PR TITLE
Local (GHA) and binder baltrad installation

### LINKED ISSUE #18: Install baltrad into book environment
If we want to automatically run the notebooks which are using baltrad on book build, we need to install baltrad into that environment too. That is different from the binder, but we can use the same procedure there.

### PR DESCRIPTION
**Pull request by kmuehlbauer**
I've rearranged the installation process:

- install scripts are moved to install-folder
- installation is working transparently for binder and local (GHA) setup

Please note also that I've added a script which strips the notebook output plus kernelspec from the notebooks. It would be great if we could only allow notebooks without output cells and kernelspec metadata to be imported into the git.

For the course notebooks I would recommend that we incorporate all needed notebooks into this repository so that people do not need to download them by themselves. 

closes #18

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Since the baltrad notebooks are pulled in in GHA, they are not available in the `._toc` and therefore they are not linked in the document.

But we can access them by the known path, eg.

https://openradarscience.org/erad2022/_preview/22/notebooks/baltrad_short_course/BALTRAD%20QC.html

**Comment by kmuehlbauer** [comment]
For the binder you can check at my fork: https://binder-staging.2i2c.cloud/v2/gh/kmuehlbauer/erad2022/local-baltrad?labpath=notebooks (currently building).

**Comment by kmuehlbauer** [comment]
I've updated the baltrad2wradlib notebook, so we can examine it:

https://openradarscience.org/erad2022/_preview/22/notebooks/baltrad2wradlib/baltrad2wradlib.html

**Review by mgrover1 — APPROVED** [review]
Great! Thanks @kmuehlbauer for figuring this out

**Comment by mgrover1** [comment]
@kmuehlbauer you okay if we merge?

**Comment by kmuehlbauer** [comment]
Sure, go ahead. 😃

**Pull request merged**
